// Code generated by protoc-gen-zig
///! package tero.policy.v1
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;
/// import package google.api
const google_api = @import("../../google/api.pb.zig");
/// import package opentelemetry.proto.common.v1
const opentelemetry_proto_common_v1 = @import("../../opentelemetry/proto/common/v1.pb.zig");

/// AttributePath specifies how to access an attribute value.
///
/// The path is represented as an array of string segments. Each segment represents
/// a key to traverse into nested maps.
///
/// Example usage:
///
/// For an attribute structure like:
/// Attributes: map[string]any{
/// "http": map[string]any{
/// "method":      "POST",
/// "status_code": 200,
/// },
/// "user_id": "u123",
/// }
///
/// - To access "user_id": ["user_id"]
/// - To access http.method: ["http", "method"]
///
/// YAML/JSON Unmarshaling:
///
/// Implementations MUST accept both the canonical proto form and shorthand forms
/// for ergonomic policy authoring:
///
/// Canonical (proto-native):
/// log_attribute:
/// path: ["http", "method"]
///
/// Shorthand array (MUST be supported):
/// log_attribute: ["http", "method"]
///
/// Shorthand string (MUST be supported for single-segment paths):
/// log_attribute: "user_id"           # equivalent to ["user_id"]
///
/// When marshaling, implementations SHOULD use the shorthand array form for
/// cleaner output.
pub const AttributePath = struct {
    path: std.ArrayListUnmanaged([]const u8) = .empty,

    pub const _desc_table = .{
        .path = fd(1, .{ .repeated = .{ .scalar = .string } }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogField identifies simple log fields (non-keyed).
pub const LogField = enum(i32) {
    LOG_FIELD_UNSPECIFIED = 0,
    LOG_FIELD_BODY = 1,
    LOG_FIELD_SEVERITY_TEXT = 2,
    LOG_FIELD_TRACE_ID = 3,
    LOG_FIELD_SPAN_ID = 4,
    LOG_FIELD_EVENT_NAME = 5,
    LOG_FIELD_RESOURCE_SCHEMA_URL = 10,
    LOG_FIELD_SCOPE_SCHEMA_URL = 11,
    _,
};

/// LogTarget defines matching and actions for logs.
pub const LogTarget = struct {
    match: std.ArrayListUnmanaged(LogMatcher) = .empty,
    keep: []const u8 = &.{},
    transform: ?LogTransform = null,
    sample_key: ?LogSampleKey = null,

    pub const _desc_table = .{
        .match = fd(1, .{ .repeated = .submessage }),
        .keep = fd(2, .{ .scalar = .string }),
        .transform = fd(3, .submessage),
        .sample_key = fd(4, .submessage),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogSampleKey specifies which field to use as the sampling key for consistent
/// sampling decisions.
pub const LogSampleKey = struct {
    field: ?field_union = null,

    pub const _field_case = enum {
        log_field,
        log_attribute,
        resource_attribute,
        scope_attribute,
    };
    pub const field_union = union(_field_case) {
        log_field: LogField,
        log_attribute: AttributePath,
        resource_attribute: AttributePath,
        scope_attribute: AttributePath,
        pub const _desc_table = .{
            .log_field = fd(1, .@"enum"),
            .log_attribute = fd(2, .submessage),
            .resource_attribute = fd(3, .submessage),
            .scope_attribute = fd(4, .submessage),
        };
    };

    pub const _desc_table = .{
        .field = fd(null, .{ .oneof = field_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogMatcher provides a way to match against log telemetry data using known fields.
///
/// IMPORTANT CONSTRAINTS:
/// - Multiple matchers are ANDed together: all matchers must match for the
/// overall match to succeed.
/// - The list of matchers should uniquely identify a specific pattern of telemetry
/// for that policy. Matchers should NOT be used as a catch-all; they should be
/// specific enough to target the intended telemetry precisely.
///
/// All regex fields use RE2 syntax for consistency across implementations.
pub const LogMatcher = struct {
    negate: bool = false,
    case_insensitive: bool = false,
    field: ?field_union = null,
    match: ?match_union = null,

    pub const _field_case = enum {
        log_field,
        log_attribute,
        resource_attribute,
        scope_attribute,
    };
    pub const field_union = union(_field_case) {
        log_field: LogField,
        log_attribute: AttributePath,
        resource_attribute: AttributePath,
        scope_attribute: AttributePath,
        pub const _desc_table = .{
            .log_field = fd(1, .@"enum"),
            .log_attribute = fd(2, .submessage),
            .resource_attribute = fd(3, .submessage),
            .scope_attribute = fd(4, .submessage),
        };
    };

    pub const _match_case = enum {
        exact,
        regex,
        exists,
        starts_with,
        ends_with,
        contains,
    };
    pub const match_union = union(_match_case) {
        exact: []const u8,
        regex: []const u8,
        exists: bool,
        starts_with: []const u8,
        ends_with: []const u8,
        contains: []const u8,
        pub const _desc_table = .{
            .exact = fd(10, .{ .scalar = .string }),
            .regex = fd(11, .{ .scalar = .string }),
            .exists = fd(12, .{ .scalar = .bool }),
            .starts_with = fd(13, .{ .scalar = .string }),
            .ends_with = fd(14, .{ .scalar = .string }),
            .contains = fd(15, .{ .scalar = .string }),
        };
    };

    pub const _desc_table = .{
        .negate = fd(20, .{ .scalar = .bool }),
        .case_insensitive = fd(21, .{ .scalar = .bool }),
        .field = fd(null, .{ .oneof = field_union }),
        .match = fd(null, .{ .oneof = match_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogTransform defines modifications to logs.
pub const LogTransform = struct {
    remove: std.ArrayListUnmanaged(LogRemove) = .empty,
    redact: std.ArrayListUnmanaged(LogRedact) = .empty,
    rename: std.ArrayListUnmanaged(LogRename) = .empty,
    add: std.ArrayListUnmanaged(LogAdd) = .empty,

    pub const _desc_table = .{
        .remove = fd(1, .{ .repeated = .submessage }),
        .redact = fd(2, .{ .repeated = .submessage }),
        .rename = fd(3, .{ .repeated = .submessage }),
        .add = fd(4, .{ .repeated = .submessage }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogRemove removes a field.
pub const LogRemove = struct {
    field: ?field_union = null,

    pub const _field_case = enum {
        log_field,
        log_attribute,
        resource_attribute,
        scope_attribute,
    };
    pub const field_union = union(_field_case) {
        log_field: LogField,
        log_attribute: AttributePath,
        resource_attribute: AttributePath,
        scope_attribute: AttributePath,
        pub const _desc_table = .{
            .log_field = fd(1, .@"enum"),
            .log_attribute = fd(2, .submessage),
            .resource_attribute = fd(3, .submessage),
            .scope_attribute = fd(4, .submessage),
        };
    };

    pub const _desc_table = .{
        .field = fd(null, .{ .oneof = field_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogRedact masks a field value.
pub const LogRedact = struct {
    replacement: []const u8 = &.{},
    field: ?field_union = null,

    pub const _field_case = enum {
        log_field,
        log_attribute,
        resource_attribute,
        scope_attribute,
    };
    pub const field_union = union(_field_case) {
        log_field: LogField,
        log_attribute: AttributePath,
        resource_attribute: AttributePath,
        scope_attribute: AttributePath,
        pub const _desc_table = .{
            .log_field = fd(1, .@"enum"),
            .log_attribute = fd(2, .submessage),
            .resource_attribute = fd(3, .submessage),
            .scope_attribute = fd(4, .submessage),
        };
    };

    pub const _desc_table = .{
        .replacement = fd(10, .{ .scalar = .string }),
        .field = fd(null, .{ .oneof = field_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogRename changes a field name.
pub const LogRename = struct {
    to: []const u8 = &.{},
    upsert: bool = false,
    from: ?from_union = null,

    pub const _from_case = enum {
        from_log_field,
        from_log_attribute,
        from_resource_attribute,
        from_scope_attribute,
    };
    pub const from_union = union(_from_case) {
        from_log_field: LogField,
        from_log_attribute: AttributePath,
        from_resource_attribute: AttributePath,
        from_scope_attribute: AttributePath,
        pub const _desc_table = .{
            .from_log_field = fd(1, .@"enum"),
            .from_log_attribute = fd(2, .submessage),
            .from_resource_attribute = fd(3, .submessage),
            .from_scope_attribute = fd(4, .submessage),
        };
    };

    pub const _desc_table = .{
        .to = fd(10, .{ .scalar = .string }),
        .upsert = fd(11, .{ .scalar = .bool }),
        .from = fd(null, .{ .oneof = from_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// LogAdd inserts a field.
pub const LogAdd = struct {
    value: []const u8 = &.{},
    upsert: bool = false,
    field: ?field_union = null,

    pub const _field_case = enum {
        log_field,
        log_attribute,
        resource_attribute,
        scope_attribute,
    };
    pub const field_union = union(_field_case) {
        log_field: LogField,
        log_attribute: AttributePath,
        resource_attribute: AttributePath,
        scope_attribute: AttributePath,
        pub const _desc_table = .{
            .log_field = fd(1, .@"enum"),
            .log_attribute = fd(2, .submessage),
            .resource_attribute = fd(3, .submessage),
            .scope_attribute = fd(4, .submessage),
        };
    };

    pub const _desc_table = .{
        .value = fd(10, .{ .scalar = .string }),
        .upsert = fd(11, .{ .scalar = .bool }),
        .field = fd(null, .{ .oneof = field_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// MetricField identifies simple metric fields (non-keyed).
pub const MetricField = enum(i32) {
    METRIC_FIELD_UNSPECIFIED = 0,
    METRIC_FIELD_NAME = 1,
    METRIC_FIELD_DESCRIPTION = 2,
    METRIC_FIELD_UNIT = 3,
    METRIC_FIELD_RESOURCE_SCHEMA_URL = 10,
    METRIC_FIELD_SCOPE_SCHEMA_URL = 11,
    METRIC_FIELD_SCOPE_NAME = 12,
    METRIC_FIELD_SCOPE_VERSION = 13,
    _,
};

/// MetricType identifies the type of metric for matching.
pub const MetricType = enum(i32) {
    METRIC_TYPE_UNSPECIFIED = 0,
    METRIC_TYPE_GAUGE = 1,
    METRIC_TYPE_SUM = 2,
    METRIC_TYPE_HISTOGRAM = 3,
    METRIC_TYPE_EXPONENTIAL_HISTOGRAM = 4,
    METRIC_TYPE_SUMMARY = 5,
    _,
};

/// AggregationTemporality defines how a metric aggregator reports aggregated values.
/// Mirrors opentelemetry.proto.metrics.v1.AggregationTemporality.
pub const AggregationTemporality = enum(i32) {
    AGGREGATION_TEMPORALITY_UNSPECIFIED = 0,
    AGGREGATION_TEMPORALITY_DELTA = 1,
    AGGREGATION_TEMPORALITY_CUMULATIVE = 2,
    _,
};

/// MetricTarget defines matching and actions for metrics.
pub const MetricTarget = struct {
    match: std.ArrayListUnmanaged(MetricMatcher) = .empty,
    keep: bool = false,

    pub const _desc_table = .{
        .match = fd(1, .{ .repeated = .submessage }),
        .keep = fd(2, .{ .scalar = .bool }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// MetricMatcher provides a way to match against metric telemetry data using known fields.
///
/// IMPORTANT CONSTRAINTS:
/// - Multiple matchers are ANDed together: all matchers must match for the
/// overall match to succeed.
/// - The list of matchers should uniquely identify a specific pattern of telemetry
/// for that policy. Matchers should NOT be used as a catch-all; they should be
/// specific enough to target the intended telemetry precisely.
///
/// All regex fields use RE2 syntax for consistency across implementations.
pub const MetricMatcher = struct {
    negate: bool = false,
    case_insensitive: bool = false,
    field: ?field_union = null,
    match: ?match_union = null,

    pub const _field_case = enum {
        metric_field,
        datapoint_attribute,
        resource_attribute,
        scope_attribute,
        metric_type,
        aggregation_temporality,
    };
    pub const field_union = union(_field_case) {
        metric_field: MetricField,
        datapoint_attribute: AttributePath,
        resource_attribute: AttributePath,
        scope_attribute: AttributePath,
        metric_type: MetricType,
        aggregation_temporality: AggregationTemporality,
        pub const _desc_table = .{
            .metric_field = fd(1, .@"enum"),
            .datapoint_attribute = fd(2, .submessage),
            .resource_attribute = fd(3, .submessage),
            .scope_attribute = fd(4, .submessage),
            .metric_type = fd(5, .@"enum"),
            .aggregation_temporality = fd(6, .@"enum"),
        };
    };

    pub const _match_case = enum {
        exact,
        regex,
        exists,
        starts_with,
        ends_with,
        contains,
    };
    pub const match_union = union(_match_case) {
        exact: []const u8,
        regex: []const u8,
        exists: bool,
        starts_with: []const u8,
        ends_with: []const u8,
        contains: []const u8,
        pub const _desc_table = .{
            .exact = fd(10, .{ .scalar = .string }),
            .regex = fd(11, .{ .scalar = .string }),
            .exists = fd(12, .{ .scalar = .bool }),
            .starts_with = fd(13, .{ .scalar = .string }),
            .ends_with = fd(14, .{ .scalar = .string }),
            .contains = fd(15, .{ .scalar = .string }),
        };
    };

    pub const _desc_table = .{
        .negate = fd(20, .{ .scalar = .bool }),
        .case_insensitive = fd(21, .{ .scalar = .bool }),
        .field = fd(null, .{ .oneof = field_union }),
        .match = fd(null, .{ .oneof = match_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// TraceField identifies simple span fields (non-keyed).
pub const TraceField = enum(i32) {
    TRACE_FIELD_UNSPECIFIED = 0,
    TRACE_FIELD_NAME = 1,
    TRACE_FIELD_TRACE_ID = 2,
    TRACE_FIELD_SPAN_ID = 3,
    TRACE_FIELD_PARENT_SPAN_ID = 4,
    TRACE_FIELD_TRACE_STATE = 5,
    TRACE_FIELD_RESOURCE_SCHEMA_URL = 10,
    TRACE_FIELD_SCOPE_SCHEMA_URL = 11,
    TRACE_FIELD_SCOPE_NAME = 12,
    TRACE_FIELD_SCOPE_VERSION = 13,
    _,
};

/// SpanKind identifies the type of span for matching.
/// Mirrors opentelemetry.proto.trace.v1.Span.SpanKind.
pub const SpanKind = enum(i32) {
    SPAN_KIND_UNSPECIFIED = 0,
    SPAN_KIND_INTERNAL = 1,
    SPAN_KIND_SERVER = 2,
    SPAN_KIND_CLIENT = 3,
    SPAN_KIND_PRODUCER = 4,
    SPAN_KIND_CONSUMER = 5,
    _,
};

/// SpanStatusCode identifies the span status for matching.
/// Mirrors opentelemetry.proto.trace.v1.Status.StatusCode.
pub const SpanStatusCode = enum(i32) {
    SPAN_STATUS_CODE_UNSPECIFIED = 0,
    SPAN_STATUS_CODE_OK = 1,
    SPAN_STATUS_CODE_ERROR = 2,
    _,
};

/// SamplingMode determines how the sampling decision is made.
pub const SamplingMode = enum(i32) {
    SAMPLING_MODE_UNSPECIFIED = 0,
    SAMPLING_MODE_HASH_SEED = 1,
    SAMPLING_MODE_PROPORTIONAL = 2,
    SAMPLING_MODE_EQUALIZING = 3,
    _,
};

/// TraceTarget defines matching and sampling actions for traces/spans.
pub const TraceTarget = struct {
    match: std.ArrayListUnmanaged(TraceMatcher) = .empty,
    keep: ?TraceSamplingConfig = null,

    pub const _desc_table = .{
        .match = fd(1, .{ .repeated = .submessage }),
        .keep = fd(2, .submessage),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// TraceMatcher provides a way to match against trace/span telemetry data using known fields.
///
/// IMPORTANT CONSTRAINTS:
/// - Multiple matchers are ANDed together: all matchers must match for the
/// overall match to succeed.
/// - The list of matchers should uniquely identify a specific pattern of telemetry
/// for that policy. Matchers should NOT be used as a catch-all; they should be
/// specific enough to target the intended telemetry precisely.
///
/// All regex fields use RE2 syntax for consistency across implementations.
pub const TraceMatcher = struct {
    negate: bool = false,
    case_insensitive: bool = false,
    field: ?field_union = null,
    match: ?match_union = null,

    pub const _field_case = enum {
        trace_field,
        span_attribute,
        resource_attribute,
        scope_attribute,
        span_kind,
        span_status,
        event_name,
        event_attribute,
        link_trace_id,
    };
    pub const field_union = union(_field_case) {
        trace_field: TraceField,
        span_attribute: AttributePath,
        resource_attribute: AttributePath,
        scope_attribute: AttributePath,
        span_kind: SpanKind,
        span_status: SpanStatusCode,
        event_name: []const u8,
        event_attribute: AttributePath,
        link_trace_id: []const u8,
        pub const _desc_table = .{
            .trace_field = fd(1, .@"enum"),
            .span_attribute = fd(2, .submessage),
            .resource_attribute = fd(3, .submessage),
            .scope_attribute = fd(4, .submessage),
            .span_kind = fd(5, .@"enum"),
            .span_status = fd(6, .@"enum"),
            .event_name = fd(7, .{ .scalar = .string }),
            .event_attribute = fd(8, .submessage),
            .link_trace_id = fd(9, .{ .scalar = .string }),
        };
    };

    pub const _match_case = enum {
        exact,
        regex,
        exists,
        starts_with,
        ends_with,
        contains,
    };
    pub const match_union = union(_match_case) {
        exact: []const u8,
        regex: []const u8,
        exists: bool,
        starts_with: []const u8,
        ends_with: []const u8,
        contains: []const u8,
        pub const _desc_table = .{
            .exact = fd(10, .{ .scalar = .string }),
            .regex = fd(11, .{ .scalar = .string }),
            .exists = fd(12, .{ .scalar = .bool }),
            .starts_with = fd(13, .{ .scalar = .string }),
            .ends_with = fd(14, .{ .scalar = .string }),
            .contains = fd(15, .{ .scalar = .string }),
        };
    };

    pub const _desc_table = .{
        .negate = fd(20, .{ .scalar = .bool }),
        .case_insensitive = fd(21, .{ .scalar = .bool }),
        .field = fd(null, .{ .oneof = field_union }),
        .match = fd(null, .{ .oneof = match_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// TraceSamplingConfig configures probabilistic sampling for traces.
///
/// This configuration follows the OpenTelemetry probability sampling specification:
/// https://opentelemetry.io/docs/specs/otel/trace/tracestate-probability-sampling/
///
/// Implementations MUST follow tracestate standards to allow multi-stage sampling:
/// https://opentelemetry.io/docs/specs/otel/trace/tracestate-handling/#sampling-threshold-value-th
///
/// The sampling decision is based on comparing a 56-bit randomness value (R) against
/// a rejection threshold (T). If R >= T, the span is kept; otherwise it is dropped.
/// The threshold is derived from the configured percentage:
/// T = (1 - percentage/100) * 2^56
pub const TraceSamplingConfig = struct {
    percentage: f32 = 0,
    mode: ?SamplingMode = null,
    sampling_precision: ?u32 = null,
    hash_seed: ?u32 = null,
    fail_closed: ?bool = null,

    pub const _desc_table = .{
        .percentage = fd(1, .{ .scalar = .float }),
        .mode = fd(2, .@"enum"),
        .sampling_precision = fd(3, .{ .scalar = .uint32 }),
        .hash_seed = fd(4, .{ .scalar = .uint32 }),
        .fail_closed = fd(5, .{ .scalar = .bool }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// PolicyStage identifies the execution stage for a policy.
pub const PolicyStage = enum(i32) {
    POLICY_STAGE_UNSPECIFIED = 0,
    POLICY_STAGE_LOG_FILTER = 1,
    POLICY_STAGE_LOG_TRANSFORM = 2,
    POLICY_STAGE_METRIC_FILTER = 3,
    POLICY_STAGE_TRACE_SAMPLING = 4,
    _,
};

pub const SyncType = enum(i32) {
    SYNC_TYPE_UNSPECIFIED = 0,
    SYNC_TYPE_FULL = 1,
    _,
};

/// Policy represents a complete telemetry policy definition.
/// Policies are designed to be:
/// - Implementation Agnostic: Works in SDK, Collector, or any component
/// - Standalone: No need to understand pipeline configuration
/// - Dynamic: Can be updated post-instantiation
/// - Idempotent: Safe to apply to multiple components
/// - Fail-Open: Does not interfere with telemetry on failure
pub const Policy = struct {
    id: []const u8 = &.{},
    name: []const u8 = &.{},
    description: []const u8 = &.{},
    enabled: bool = false,
    created_at_unix_nano: u64 = 0,
    modified_at_unix_nano: u64 = 0,
    labels: std.ArrayListUnmanaged(opentelemetry_proto_common_v1.KeyValue) = .empty,
    target: ?target_union = null,

    pub const _target_case = enum {
        log,
        metric,
        trace,
    };
    pub const target_union = union(_target_case) {
        log: LogTarget,
        metric: MetricTarget,
        trace: TraceTarget,
        pub const _desc_table = .{
            .log = fd(10, .submessage),
            .metric = fd(11, .submessage),
            .trace = fd(12, .submessage),
        };
    };

    pub const _desc_table = .{
        .id = fd(1, .{ .scalar = .string }),
        .name = fd(2, .{ .scalar = .string }),
        .description = fd(3, .{ .scalar = .string }),
        .enabled = fd(4, .{ .scalar = .bool }),
        .created_at_unix_nano = fd(5, .{ .scalar = .fixed64 }),
        .modified_at_unix_nano = fd(6, .{ .scalar = .fixed64 }),
        .labels = fd(7, .{ .repeated = .submessage }),
        .target = fd(null, .{ .oneof = target_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// ClientMetadata contains information about the client requesting policies.
pub const ClientMetadata = struct {
    supported_policy_stages: std.ArrayListUnmanaged(PolicyStage) = .empty,
    labels: std.ArrayListUnmanaged(opentelemetry_proto_common_v1.KeyValue) = .empty,
    resource_attributes: std.ArrayListUnmanaged(opentelemetry_proto_common_v1.KeyValue) = .empty,

    pub const _desc_table = .{
        .supported_policy_stages = fd(1, .{ .repeated = .@"enum" }),
        .labels = fd(2, .{ .repeated = .submessage }),
        .resource_attributes = fd(3, .{ .repeated = .submessage }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// TransformStageStatus reports hits and misses for a single transform stage.
pub const TransformStageStatus = struct {
    hits: i64 = 0,
    misses: i64 = 0,

    pub const _desc_table = .{
        .hits = fd(1, .{ .scalar = .int64 }),
        .misses = fd(2, .{ .scalar = .int64 }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// PolicySyncStatus reports the status of an individual policy during sync.
/// Used to communicate policy execution metrics and errors back to the provider.
pub const PolicySyncStatus = struct {
    id: []const u8 = &.{},
    match_hits: i64 = 0,
    match_misses: i64 = 0,
    errors: std.ArrayListUnmanaged([]const u8) = .empty,
    remove: ?TransformStageStatus = null,
    redact: ?TransformStageStatus = null,
    rename: ?TransformStageStatus = null,
    add: ?TransformStageStatus = null,

    pub const _desc_table = .{
        .id = fd(1, .{ .scalar = .string }),
        .match_hits = fd(2, .{ .scalar = .int64 }),
        .match_misses = fd(3, .{ .scalar = .int64 }),
        .errors = fd(4, .{ .repeated = .{ .scalar = .string } }),
        .remove = fd(10, .submessage),
        .redact = fd(11, .submessage),
        .rename = fd(12, .submessage),
        .add = fd(13, .submessage),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// SyncRequest is sent by clients to request policy updates.
pub const SyncRequest = struct {
    client_metadata: ?ClientMetadata = null,
    full_sync: bool = false,
    last_sync_timestamp_unix_nano: u64 = 0,
    last_successful_hash: []const u8 = &.{},
    policy_statuses: std.ArrayListUnmanaged(PolicySyncStatus) = .empty,

    pub const _desc_table = .{
        .client_metadata = fd(1, .submessage),
        .full_sync = fd(2, .{ .scalar = .bool }),
        .last_sync_timestamp_unix_nano = fd(3, .{ .scalar = .fixed64 }),
        .last_successful_hash = fd(4, .{ .scalar = .string }),
        .policy_statuses = fd(5, .{ .repeated = .submessage }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};

/// SyncResponse contains policy updates for the client.
pub const SyncResponse = struct {
    policies: std.ArrayListUnmanaged(Policy) = .empty,
    hash: []const u8 = &.{},
    sync_timestamp_unix_nano: u64 = 0,
    recommended_sync_interval_seconds: u32 = 0,
    sync_type: SyncType = @enumFromInt(0),
    error_message: []const u8 = &.{},

    pub const _desc_table = .{
        .policies = fd(1, .{ .repeated = .submessage }),
        .hash = fd(2, .{ .scalar = .string }),
        .sync_timestamp_unix_nano = fd(3, .{ .scalar = .fixed64 }),
        .recommended_sync_interval_seconds = fd(4, .{ .scalar = .uint32 }),
        .sync_type = fd(5, .@"enum"),
        .error_message = fd(6, .{ .scalar = .string }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

    /// This method is used by std.json
    /// internally for serialization. DO NOT RENAME!
    pub fn jsonStringify(self: *const @This(), jws: anytype) !void {
        return protobuf.json.stringify(@This(), self, jws);
    }
};
